### ISSUE TITLE
TODO Front 4

### ISSUE THREAD

**Issue by syntaxerro** [syntaxerro/Mirror#4]
- [ ] Powiększenie menu (mobilne)
- [x] Lista z komentarzami
    - Nazwa użytkownika
    - Data i czas
    - Treść komentarza
- [ ] Plus na przycisku z formularzem uploadu. (::before nie jest czytane przez czytniki ekranowe.)
- [x] &lt;nav> wewnątrz &lt;header> + menu robi się na liście. ( &lt;ul> i &lt;li>)
- [ ] .blockCont zamienić na &lt;article> + &lt;h2> zamiast &lt;h1> wewnątrz niego.
- [ ] W tym &lt;h2> zostawiłbym sam link, natomiast ten &lt;span> i datę wyciągnąłbym na zewnątrz i całość otoczył &lt;header>. Dodatkowo nie ma etykietek dla daty i tej liczby. Można je dodać przy pomocy .visuallyhidden.
- [ ] http://www.stevesouders.com/blog/2009/04/09/dont-use-import/ Czcionka w &lt;head>.
- [ ] JS: Zamiast się babrać z .blockConts poleciałbym przy pomocy event delegation. Wówczas będziemy mieli jeden listener zamiast n listenerów.
- [x] Data i czas wewnątrz tagu &lt;time>
